/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author enriq
 */
public class EditAlmacen extends javax.swing.JFrame {

    private Archivotexto archivo = new Archivotexto();
    static Grafo grafo;

    /**
     * Creates new form OptionSelection
     */
    public EditAlmacen(Grafo grafo) {
        initComponents();
        this.grafo = grafo;
        setLocationRelativeTo(null);

        // Proceder a meter las vainas en la clase
        Almacen pointer = grafo.getLista().getFirst();

        while (pointer != null) {

            Almacenes.addItem(pointer.getName());

            pointer = pointer.getNext();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        Almacenes = new javax.swing.JComboBox<>();
        Almacenes2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Numero1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Producto2 = new javax.swing.JTextField();
        Numero2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        OK2 = new javax.swing.JButton();
        OK3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ADD STOCK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 90, -1));

        jLabel2.setText("Indique el Almacen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, -1));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 100));

        Almacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenesActionPerformed(evt);
            }
        });
        jPanel1.add(Almacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        Almacenes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Almacenes2ActionPerformed(evt);
            }
        });
        jPanel1.add(Almacenes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        jLabel3.setText("AGREGAR  PRODUCTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, -1));

        Numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero1ActionPerformed(evt);
            }
        });
        jPanel1.add(Numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, -1));

        jLabel4.setText("NUEVO PRODUCTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        Producto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producto2ActionPerformed(evt);
            }
        });
        jPanel1.add(Producto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 80, -1));

        Numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero2ActionPerformed(evt);
            }
        });
        jPanel1.add(Numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 80, -1));

        jLabel5.setText("producto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel6.setText("numero");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jLabel7.setText("numero");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        OK2.setText("OK");
        OK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK2ActionPerformed(evt);
            }
        });
        jPanel1.add(OK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        OK3.setText("OK");
        OK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK3ActionPerformed(evt);
            }
        });
        jPanel1.add(OK3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel8.setText("producto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 60, -1));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 80, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/pixels-video-games-wallpaper-preview.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 510, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Almacenes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Almacenes2ActionPerformed


    }//GEN-LAST:event_Almacenes2ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String opcion = Almacenes.getSelectedItem().toString();
        String texto = "";

        Almacen pointer = grafo.getLista().getFirst();
        
//        NodoStock pointerstock= grafo.getLista().getFirst().
        
        while (!pointer.getName().equalsIgnoreCase(opcion)) {

            pointer = pointer.getNext();
        }

        texto = texto + Almacenes.getSelectedItem().toString() + "\n";

        if (!pointer.getLista().isEmpty()) {
            NodoStock pointer2 = pointer.getLista().getFirst();
            while (pointer2 != null) {

                texto = texto + "producto: " + pointer2.getName() + "-->" + pointer2.getData() + "\n";
                pointer2 = pointer2.getNext();
            }
            AreaTexto.setText(texto);

            if (!pointer.getLista().isEmpty()) {
                NodoStock pointer3 = pointer.getLista().getFirst();
                while (pointer3 != null) {

                    Almacenes2.addItem(pointer3.getName());

                    pointer3 = pointer3.getNext();

                }

            }

        }


    }//GEN-LAST:event_okActionPerformed

    private void AlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenesActionPerformed


    }//GEN-LAST:event_AlmacenesActionPerformed

    private void OK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK2ActionPerformed
        String opcion = Almacenes.getSelectedItem().toString();
        String texto = "";

        //CONFIRMAR QUE ES UN NUMERO
        int Numero = Integer.parseInt(Numero1.getText());
        
         if (Numero1.getText().equals("")) {

            Numero = 0;

        } else {
            Numero = Integer.parseInt(Numero1.getText());
        }
        
        
        
        
        Almacen pointer = grafo.getLista().getFirst();

        while (!pointer.getName().equalsIgnoreCase(opcion)) {

            pointer = pointer.getNext();
        }

        if (!pointer.getLista().isEmpty()) {
            NodoStock pointer3 = pointer.getLista().getFirst();
            while (!pointer3.getName().equalsIgnoreCase(Almacenes2.getSelectedItem().toString())) {

                pointer3 = pointer3.getNext();

            }

            pointer3.setData(pointer3.getData() + Numero);
        }

        texto = texto + Almacenes.getSelectedItem().toString() + "\n";

        if (!pointer.getLista().isEmpty()) {
            NodoStock pointer2 = pointer.getLista().getFirst();
            while (pointer2 != null) {

                texto = texto + "producto: " + pointer2.getName() + "-->" + pointer2.getData() + "\n";
                pointer2 = pointer2.getNext();
            }
            AreaTexto.setText(texto);

        }

        Numero1.setText("");
    }//GEN-LAST:event_OK2ActionPerformed

    private void Numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Numero1ActionPerformed

    private void Numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Numero2ActionPerformed

    private void OK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK3ActionPerformed
        // Confirmar que es un numero

        System.out.println("da");
        String opcion = Almacenes.getSelectedItem().toString();
        String producto = "";
        String texto = "";
        int numero = 0;

        if (Numero2.getText().equals("")) {

            numero = 0;

        } else {
            numero = Integer.parseInt(Numero2.getText());
        }

        //confirmar que numero2 tiene que estar y ser numero
        if (Producto2.getText().equalsIgnoreCase("pantalla") || Producto2.getText().equalsIgnoreCase("ram") || Producto2.getText().equalsIgnoreCase("grafica") || Producto2.getText().equalsIgnoreCase("placa") || Producto2.getText().equalsIgnoreCase("teclado") || Producto2.getText().equalsIgnoreCase("mouse") || Producto2.getText().equalsIgnoreCase("microfono") || Producto2.getText().equalsIgnoreCase("audifono")) {
            System.out.println("si");
            if (Producto2.getText().equalsIgnoreCase("pantalla")) {
                producto = "Pantalla";

            } else if (Producto2.getText().equalsIgnoreCase("grafica")) {
                producto = "Grafica";
            } else if (Producto2.getText().equalsIgnoreCase("ram")) {
                producto = "RAM";

            } else if (Producto2.getText().equalsIgnoreCase("placa")) {
                producto = "Placa";
            } else if (Producto2.getText().equalsIgnoreCase("teclado")) {
                producto = "Teclado";
                System.out.println("es teclado");
                System.out.println(producto);
            } else if (Producto2.getText().equalsIgnoreCase("mouse")) {
                producto = "Mouse";

            } else if (Producto2.getText().equalsIgnoreCase("microfono")) {
                producto = "Microfono";

            } else if (Producto2.getText().equalsIgnoreCase("audifono")) {
                producto = "Audifono";
            }

            Almacen pointer = grafo.getLista().getFirst();

            while (!pointer.getName().equalsIgnoreCase(opcion)) {

                pointer = pointer.getNext();
            }

            System.out.println("en almacen");
            NodoStock pointer3 = pointer.getLista().getFirst();
            while (pointer3 != null) {

                if (pointer3.getName().equals(producto) && !pointer3.getName().equalsIgnoreCase("")) {
                    break;
                }

                pointer3 = pointer3.getNext();

            }
            if (pointer3 == null) {
                System.out.println("no esta en la lista");

            } else {
                System.out.println("si esta");
            }

            if (pointer3 == null) {

                pointer.getLista().InsertFinal(producto, numero);

            }

            texto = texto + Almacenes.getSelectedItem().toString() + "\n";
            NodoStock pointer2 = pointer.getLista().getFirst();
            while (pointer2 != null) {

                texto = texto + "producto: " + pointer2.getName() + "-->" + pointer2.getData() + "\n";
                pointer2 = pointer2.getNext();
            }
            AreaTexto.setText(texto);

        } else {
            System.out.println("no");
            AreaTexto.setText("Este producto No esta en Stock");

        }

        Numero2.setText("");

        Producto2.setText("");


    }//GEN-LAST:event_OK3ActionPerformed

    private void Producto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Producto2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            OptionSelection window2 = new OptionSelection(grafo);
        window2.show();
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAlmacen(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Almacenes;
    private javax.swing.JComboBox<String> Almacenes2;
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JTextField Numero1;
    private javax.swing.JTextField Numero2;
    private javax.swing.JButton OK2;
    private javax.swing.JButton OK3;
    private javax.swing.JTextField Producto2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
