/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author enriq
 */
public class GUIPedidos extends javax.swing.JFrame {

    private Archivotexto archivo = new Archivotexto();
    static Grafo grafo;

    /**
     * Creates new form OptionSelection
     */
    public GUIPedidos(Grafo grafo) {
        initComponents();
        this.grafo = grafo;
        setLocationRelativeTo(null);

        // Proceder a meter las opciones en el jcombobox
        Almacen pointer = grafo.getLista().getFirst();

        while (pointer != null) {

            Almacenes.addItem(pointer.getName());

            pointer = pointer.getNext();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        Almacenes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Almacenes2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        pedido = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jPanel1.add(Almacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setText("Almacen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, -1));

        jLabel3.setText("Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, -1));

        Almacenes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Almacenes2ActionPerformed(evt);
            }
        });
        jPanel1.add(Almacenes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });
        jPanel1.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 80, -1));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        pedido.setText("Hacer Pedido");
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        jPanel1.add(pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Sistemas Shop");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 130, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/pixels-video-games-wallpaper-preview.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -80, 530, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Almacenes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Almacenes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Almacenes2ActionPerformed

    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        String opcion = Almacenes.getSelectedItem().toString();
        String texto = "";

        Almacen pointer = grafo.getLista().getFirst();
        //recorrer el nodo hasta que sea la opción
        while (!pointer.getName().equalsIgnoreCase(opcion)) {

            pointer = pointer.getNext();
        }

        texto = texto + Almacenes.getSelectedItem().toString() + "\n";

        if (!pointer.getLista().isEmpty()) {
            //recorrer los productos del almacen para imprimirlos
            NodoStock pointer2 = pointer.getLista().getFirst();
            while (pointer2 != null) {

                texto = texto + "producto: " + pointer2.getName() + "-->" + pointer2.getData() + "\n";
                pointer2 = pointer2.getNext();
            }
            AreaTexto.setText(texto);

            if (!pointer.getLista().isEmpty()) {
                NodoStock pointer3 = pointer.getLista().getFirst();
                while (pointer3 != null) {
                    //añadir al jcombobox
                    Almacenes2.addItem(pointer3.getName());

                    pointer3 = pointer3.getNext();

                }
            }

        }


    }//GEN-LAST:event_okActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
        //inicializar variables
        String Numero = Cantidad.getText();
        int numero=0;

        //verificar si es numero
        boolean value = true;
        try {
            Integer.parseInt(Numero);
            value = true;

        } catch (Exception e) {
            value = false;
            JOptionPane.showMessageDialog(null, "El valor que ingresa no es numérico");
        }

        if (value == true) {
            numero =Integer.parseInt(Numero);
        }
        String opcion = Almacenes.getSelectedItem().toString();
        String texto = "";
        Almacen pointer = grafo.getLista().getFirst();

        while (!pointer.getName().equalsIgnoreCase(opcion)) {

            pointer = pointer.getNext();
        }

        if (!pointer.getLista().isEmpty()) {
            NodoStock pointer3 = pointer.getLista().getFirst();
            while (!pointer3.getName().equalsIgnoreCase(Almacenes2.getSelectedItem().toString())) {

                pointer3 = pointer3.getNext();

            }

            if (pointer3.getData() >= numero) {

                pointer3.setData(pointer3.getData() - numero);
            } else {
                JOptionPane.showMessageDialog(null, "Mayor cantidad de la que hay en el almacen");
                System.out.println("TOCA DIJSTRA");

            }
        }

        texto = texto + Almacenes.getSelectedItem().toString() + "\n";

        if (!pointer.getLista().isEmpty()) {
            NodoStock pointer2 = pointer.getLista().getFirst();
            while (pointer2 != null) {

                texto = texto + "producto: " + pointer2.getName() + "-->" + pointer2.getData() + "\n";
                pointer2 = pointer2.getNext();
            }
            AreaTexto.setText(texto);

        }

        Cantidad.setText("");


    }//GEN-LAST:event_pedidoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        //cerrar ventana y abrir sig ventana
        OptionSelection window2 = new OptionSelection(grafo);
        window2.show();
        this.dispose();


    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPedidos(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Almacenes;
    private javax.swing.JComboBox<String> Almacenes2;
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    private javax.swing.JButton pedido;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
