/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

/**
 *
 * @author enriq
 */
public class GUIPedidos extends javax.swing.JFrame {

    private Archivotexto archivo = new Archivotexto();
    static Grafo grafo;

    /**
     * Creates new form OptionSelection
     */
    public GUIPedidos(Grafo grafo) {
        initComponents();
        this.grafo = grafo;
        setLocationRelativeTo(null);

        // Proceder a meter las vainas en la clase
        Almacen pointer = grafo.getLista().getFirst();

        while (pointer != null) {

            Almacenes.addItem(pointer.getName());

            pointer = pointer.getNext();
        }

    }
    
    
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Almacenes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Almacenes2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AreaTexto.setColumns(20);
        AreaTexto.setRows(5);
        jScrollPane1.setViewportView(AreaTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel1.setText("PEDIDOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 50, -1));

        jPanel1.add(Almacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setText("Almacen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, -1));

        jLabel3.setText("Producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, -1));

        Almacenes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Almacenes2ActionPerformed(evt);
            }
        });
        jPanel1.add(Almacenes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });
        jPanel1.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 80, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jButton2.setText("Hacer Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Almacenes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Almacenes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Almacenes2ActionPerformed

    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String opcion = Almacenes.getSelectedItem().toString();
        String texto = "";

        Almacen pointer = grafo.getLista().getFirst();
        
//        NodoStock pointerstock= grafo.getLista().getFirst().
        
        while (!pointer.getName().equalsIgnoreCase(opcion)) {

            pointer = pointer.getNext();
        }

        texto = texto + Almacenes.getSelectedItem().toString() + "\n";

        if (!pointer.getLista().isEmpty()) {
            NodoStock pointer2 = pointer.getLista().getFirst();
            while (pointer2 != null) {

                texto = texto + "producto: " + pointer2.getName() + "-->" + pointer2.getData() + "\n";
                pointer2 = pointer2.getNext();
            }
            AreaTexto.setText(texto);
            
            if (!pointer.getLista().isEmpty()) {
                NodoStock pointer3 = pointer.getLista().getFirst();
                while (pointer3 != null) {

                    Almacenes2.addItem(pointer3.getName());

                    pointer3 = pointer3.getNext();

                }
        }
        
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int Numero = 0;
        
        
        
        
        if (Cantidad.getText().equals("")) {

            Numero = 0;

        } else {
            Numero = Integer.parseInt(Cantidad.getText());
        }
        
        
        String opcion = Almacenes.getSelectedItem().toString();
        String texto="";
        Almacen pointer = grafo.getLista().getFirst();

        while (!pointer.getName().equalsIgnoreCase(opcion)) {

            pointer = pointer.getNext();
        }
        
        
        if (!pointer.getLista().isEmpty()) {
            NodoStock pointer3 = pointer.getLista().getFirst();
            while (!pointer3.getName().equalsIgnoreCase(Almacenes2.getSelectedItem().toString())) {

                pointer3 = pointer3.getNext();

            }
            
            if (pointer3.getData()>= Numero){

            pointer3.setData(pointer3.getData() - Numero);
            }else{
                
                System.out.println("TOCA DIJSTRA");
//                AQUI ES DONDE LUIS DEBE DE PONER SU FUNCION Y BUSCAR EN ALMACENES MAS CERCANO EL RPODUCTO
                
                
                
                
            }
        }

        texto = texto + Almacenes.getSelectedItem().toString() + "\n";

        if (!pointer.getLista().isEmpty()) {
            NodoStock pointer2 = pointer.getLista().getFirst();
            while (pointer2 != null) {

                texto = texto + "producto: " + pointer2.getName() + "-->" + pointer2.getData() + "\n";
                pointer2 = pointer2.getNext();
            }
            AreaTexto.setText(texto);

        }

        Cantidad.setText("");
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  OptionSelection window2 = new OptionSelection(grafo);
        window2.show();
        this.setVisible(false);        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPedidos(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Almacenes;
    private javax.swing.JComboBox<String> Almacenes2;
    private javax.swing.JTextArea AreaTexto;
    private javax.swing.JTextField Cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
