/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import static Proyecto.ImportMenu.grafo;
import javax.swing.JOptionPane;

/**
 *
 * @author <Joseph Ruiz EDD Unimet>
 */
public class OptionSelection extends javax.swing.JFrame {

    private Archivotexto archivo = new Archivotexto();
    static Grafo grafo;
    private ShowGraph mostrarGrafo=new ShowGraph(grafo);

    /**
     * Creates new form GUI2
     */
    public OptionSelection(Grafo grafo) {
        initComponents();
        this.grafo = grafo;
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        export = new javax.swing.JButton();
        editalmacen = new javax.swing.JButton();
        pedido = new javax.swing.JButton();
        editgrafo = new javax.swing.JButton();
        showgrafo = new javax.swing.JButton();
        recorridos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Sistemas Shop");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, -1));

        export.setText("Exportar");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        jPanel1.add(export, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        editalmacen.setText("Edit Almacen");
        editalmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editalmacenActionPerformed(evt);
            }
        });
        jPanel1.add(editalmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 50));

        pedido.setText("Hacer Pedido");
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        jPanel1.add(pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 120, 50));

        editgrafo.setText("Edit Grafo");
        editgrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editgrafoActionPerformed(evt);
            }
        });
        jPanel1.add(editgrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 50));

        showgrafo.setText("Grafo");
        showgrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showgrafoActionPerformed(evt);
            }
        });
        jPanel1.add(showgrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, 50));

        recorridos.setText("Recorrer grafo");
        recorridos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recorridosActionPerformed(evt);
            }
        });
        jPanel1.add(recorridos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 130, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/pixels-video-games-wallpaper-preview.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 490, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        archivo.escribir_txt(grafo);
    }//GEN-LAST:event_exportActionPerformed

    private void editalmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editalmacenActionPerformed
        EditAlmacen window2 = new EditAlmacen(grafo);
        window2.show();
        this.dispose();


    }//GEN-LAST:event_editalmacenActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed

        GUIPedidos window3 = new GUIPedidos(grafo);
        window3.show();
        this.dispose();


    }//GEN-LAST:event_pedidoActionPerformed

    private void editgrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editgrafoActionPerformed

        EditGrafo window3 = new EditGrafo(grafo);
        window3.show();
        this.dispose();


    }//GEN-LAST:event_editgrafoActionPerformed

    private void recorridosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recorridosActionPerformed
        GUIShowStock window4 = new GUIShowStock(grafo);
        window4.show();
        this.dispose();
     }//GEN-LAST:event_recorridosActionPerformed

    private void showgrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showgrafoActionPerformed
        mostrarGrafo.ShowGraph(grafo);

        
    }//GEN-LAST:event_showgrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionSelection(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editalmacen;
    private javax.swing.JButton editgrafo;
    private javax.swing.JButton export;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pedido;
    private javax.swing.JButton recorridos;
    private javax.swing.JButton showgrafo;
    // End of variables declaration//GEN-END:variables
}
